version: 2

# Define el sistema operativo y herramientas
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"

# Define el formato y dónde están los archivos (ejemplo usando MkDocs)
mkdocs:
  configuration: mkdocs.yml
