site_name: TLfloress Documentación
theme:
  name: readthedocs

plugins:
  - search
  - print-site  # Añade esta línea

nav:
  - Inicio: index.md
  - Prueba de Imagen:
      - Vista General: prueba.md
      - Análisis Táctico: pruebas/estrategia.md
