site_name: TLfloress Documentación

theme:
  name: readthedocs
  custom_dir: overrides

plugins:
  - search
  - print-site

nav:
  - Inicio: index.md
  - Prueba de Imagen:
      - Vista General: prueba.md
      - Análisis Táctico: estrategia.md

markdown_extensions:
  - toc:
      permalink: false
